FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["exec uvicorn service.events_parser.cron_app:app --host 0.0.0.0 --port ${PORT:-8080}"]
